"""empty message

Revision ID: 77e82f27a49b
Revises: d2aa003a921b
Create Date: 2019-04-14 19:17:42.123023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e82f27a49b'
down_revision = 'd2aa003a921b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artigo', sa.Integer(), nullable=False),
    sa.Column('processo', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delitos_usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('delito_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delito_id'], ['delitos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delitos_usuario')
    op.drop_table('delitos')
    # ### end Alembic commands ###
