"""empty message

Revision ID: 87b9b825daca
Revises: 784e6de21146
Create Date: 2019-02-17 11:17:16.833424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b9b825daca'
down_revision = '784e6de21146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('ddd', sa.String(length=5), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('operadora', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('atributos', sa.Column('endereco_id', sa.Integer(), nullable=True))
    op.add_column('atributos', sa.Column('telefone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atributos', 'enderecos', ['endereco_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'atributos', 'telefones', ['telefone_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atributos', type_='foreignkey')
    op.drop_constraint(None, 'atributos', type_='foreignkey')
    op.drop_column('atributos', 'telefone_id')
    op.drop_column('atributos', 'endereco_id')
    op.drop_table('telefones')
    op.drop_table('enderecos')
    # ### end Alembic commands ###
